### ISSUE TITLE
Fuck download in README not work!!!!

### ISSUE THREAD

**Issue by itsk1mlot** [95426pm0m/FuckV3#1]
Fuck download link in README is return Not Found.
![Screenshot_20240329_191342_Chrome](https://github.com/95426pm0m/FuckV3/assets/112325787/21381a30-c8ba-4f09-a527-5ad664db3b11)

**Comment by 95426pm0m** [comment]
Will work from now on, Un-set Pre-release of [v0.0.1a](https://github.com/95426pm0m/FuckV3/releases/tag/v0.0.1a)

**Comment by 95426pm0m** [comment]
아직 안되네 ㅎㅎㅈㅅ

**Comment by 95426pm0m** [comment]
Now it will probably work, close if solved before i close

**Comment by 95426pm0m** [comment]
What has been changed:
release v0.0.1a: Unset 'Pre-release'
README.md: fixed url (/latest/app-release.apk => /latest/download/app-release.apk)

**Comment by DevFuha** [comment]
you too ugly

**Comment by itsk1mlot** [comment]
ur mom

**Comment by 95426pm0m** [comment]
> ur mom @DevFuha 

ㅋㅋㅋㅋㅋ

**Comment by 95426pm0m** [comment]
> you too ugly hot 2 fix
> 

느금마

**Comment by DevFuha** [comment]
@itsk1mlot  니애미

**Comment by 95426pm0m** [comment]
아 섹스하고 싶다~~~~~~~
